# Generated by Django 5.1.3 on 2024-11-30 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=120)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='The Principal Amount of Loan.', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='The annual interest rate for the loan (percentage).', max_digits=5)),
                ('tenure_months', models.PositiveIntegerField(help_text='The loan tenure in months.')),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, help_text='The calculated monthly installment for this loan.', max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ('-created_at',),
            },
        ),
    ]
